spring:
  data:
    mongodb:
      uri: mongodb+srv://ayushiiijani:2orb08uyNW5737Wt@cluster0.8c1yx1w.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
      database: journaldb
      auto-index-creation: true


server:
  servlet:
    context-path: /journalapp
